acceptance_tests:
  basic_read:
    tests:
    - config_path: secrets/config.json
      empty_streams:
      - name: airbyte_camp_sp
        bypass_reason: "can't populate stream because it requires real ad campaign"
      - name: airbyte_camp_adgroups_sp
        bypass_reason: "can't populate stream because it requires real ad campaign"
      - name: airbyte_camp_placement_sp
        bypass_reason: "can't populate stream because it requires real ad campaign"
      - name: airbyte_targeting_sp
        bypass_reason: "can't populate stream because it requires real ad campaign"
      - name: airbyte_search_term_sp
        bypass_reason: "can't populate stream because it requires real ad campaign"
      - name: airbyte_advertised_product_sp
        bypass_reason: "can't populate stream because it requires real ad campaign"
      - name: airbyte_purchased_product_sp
        bypass_reason: "can't populate stream because it requires real ad campaign"
      timeout_seconds: 2400
      expect_records:
        path: integration_tests/expected_records.jsonl
  connection:
    tests:
    - config_path: secrets/config.json
      status: succeed
    - config_path: integration_tests/invalid_config.json
      status: failed
  discovery:
    tests:
    - config_path: secrets/config.json
  full_refresh:
    tests:
    - config_path: secrets/config.json
      configured_catalog_path: integration_tests/configured_catalog.json
    - config_path: secrets/config_report.json
      configured_catalog_path: integration_tests/configured_catalog_report.json
      timeout_seconds: 3600
  incremental:
    tests:
    - config_path: secrets/config_report.json
      configured_catalog_path: integration_tests/configured_catalog_report.json
      cursor_paths:
        sponsored_products_report_stream:
        - '1861552880916640'
        - reportDate
      future_state:
        future_state_path: integration_tests/abnormal_state.json
      timeout_seconds: 2400
  spec:
    tests:
    - spec_path: integration_tests/spec.json
connector_image: airbyte/source-amazon-ads:dev
test_strictness_level: high
